#!/usr/bin/env Rscript

#Taking in arguments
library("optparse")
 
option_list = list(
  make_option(c("-f", "--subtype_ratio"), type="character", default=NULL, 
              help="annotated file generated by bedtools annotate", metavar="filetype"),
  make_option(c("-o", "--order"), type="character", default=NULL, 
              help="order in which user prefers to visualize results. 1stcol:order number; 2ndcol:Filename; 3rdcol:Libraryname 4thcol:Cellline/Samplename, 5thcol:Replicate info", metavar="filetype"),
  make_option(c("-y", "--ymax"), type="double", default=6.0, 
              help="maximum range of heatmap [default %default] "),
  make_option(c("-m", "--ymin"), type="double", default=0.0, 
              help="maximum range of heatmap [default %default] ")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

#Checking for required input
writeLines("\n...Checking input...\n")
if (is.null(opt$subtype_ratio)){
  print_help(opt_parser)
  stop("Please specify subtype ratio file.n", call.=FALSE)
}

if (is.null(opt$order)){
  print_help(opt_parser)
  stop("Please specify order file.n", call.=FALSE)
}

#####Main Script
#1.Calling required Packages
writeLines("\n...Calling required Package(s)...\n")

library(ggthemes)
library(lemon)
library(pheatmap)
library(RColorBrewer)
library(combinat)
library(rstatix)
library(ggpubr)
library(stringr)
library(viridis)


#5.Plotting
writeLines("\n...Plotting Heatmap...\n")
subtypes<-as.data.frame(read.table(opt$subtype_ratio, sep="\t", header =T, quote="", check.names=FALSE))
mat=as.matrix(subtypes[,c(-1,-2)])
#png(paste(opt$subtype_ratio,"heatmap.png", sep="_"),width =(2+(ncol(subtypes)*0.4)), height = (4+(nrow(subtypes)*0.25)), unit ='in', res=600)
svg(paste(opt$subtype_ratio,"heatmap.svg", sep="_"),width =(2+(ncol(subtypes)*0.4)), height = (4+(nrow(subtypes)*0.25)))

x=pheatmap(mat, cluster_rows = F,cluster_cols = F, display_numbers = T, 
         breaks = c(seq(opt$ymin,1,length.out = 101)[-101], seq(1,opt$ymax,length.out = 101)),
         fontsize_number=12, number_color = "black",
         fontsize_row = 12, fontsize_col = 12,
         color=colorRampPalette(rev(brewer.pal(n=6, name = "RdBu")))(200),
         labels_row=subtypes$Group.1,
         labels_col=colnames(subtypes[,c(-1,-2)]))

print(x)
dev.off()


######################################################## BOXPLOTS ########################################################
order=as.data.frame(read.table(opt$order, sep="\t",header = F, quote=""))
colnames(order)=c("num", "Filename","Library","Cellline", "Rep")
order=order[order(order$num),]
order$lab=paste(order$Library,order$Cellline,order$Rep,sep="_")

group=gather(subtypes[,c(-2)], lab, Enrich,-Group.1)
colnames(group)[1]<-"Subtype"
finalgroup=merge(group,order[,c("Cellline","lab")])
finalgroup$Subtype=factor(finalgroup$Subtype, levels=rev(lapply(subtypes$Group.1, as.character)))
finalgroup$Cellline=factor(finalgroup$Cellline, levels=unique(lapply(order$Cellline, as.character)))
ym=ceiling(ceiling(max(mat))/2)*2


png(paste(opt$subtype_ratio,"boxplots.png", sep="_"), width =12, height =9, unit ='in', res=600)
dodge=position_dodge(width = 0.9)
ggplot(finalgroup, aes(x=Subtype, y=Enrich, fill=Subtype)) + 
   #geom_violin(width=1.4,position=dodge)+
   geom_boxplot(color="black", alpha=0.7, outlier.shape = NA,position=dodge)+
   geom_point(color="black", size=0.6, alpha=0.9)+
   facet_wrap(vars(Cellline),ncol=4, strip.position="bottom", labeller = labeller(Cellline = function(x) str_wrap(x, width = 18)))+
   scale_y_continuous(limits = c(0, ym), breaks = seq(0,ym,1))+
    scale_fill_viridis(discrete = TRUE, direction = -1)+
    geom_hline(yintercept=1,linetype=2)+
    ylab("Average Enrichment")+
    theme_classic(base_size = 18)+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.text.x=element_blank(), axis.ticks.x=element_blank())
dev.off()


writeLines("\nJob Finished.\n")
writeLines(paste("Output file name:", paste(opt$subtype_ratio,'.png\n', sep="")))
